### ISSUE TITLE
setup arquillian

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#13]

**Comment by helio-frota** [comment]
Please see or merge the pull request so others can help on the solution too.

**Comment by helio-frota** [comment]
org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not start container
    at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.startInternal(ManagedDeployableContainer.java:201)
    at org.jboss.as.arquillian.container.CommonDeployableContainer.start(CommonDeployableContainer.java:112)
    at org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:199)

...
...

Caused by: java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.startInternal(ManagedDeployableContainer.java:94)

**Comment by helio-frota** [comment]
#15

**Comment by paulojribp** [comment]
@eprogramming: @efraimgentil has add Arquillian to the project via pull request. If that works, we can close this issue right?

**Comment by helio-frota** [comment]
right.

**Comment by helio-frota** [comment]
WF (wildfly) runs ok but i always get one error
org.jboss.arquillian.test.spi.ArquillianProxyException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException : Unknown column 'sector0_.active' in 'field list' [Proxied because : Original exception not deserilizable, ClassNotFoundException]

**Comment by helio-frota** [comment]
Arquillian is ok !
The problem is only the database inconsistence.
