### ISSUE TITLE
problem with vraptor jsp publication eclipse + wildfly plugin

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#9]
![04](https://f.cloud.github.com/assets/6443576/2025481/6d59fd6a-887c-11e3-8d0d-7b186d965aa1.png)
1) run the app
2) edit some jsp
3) reload brower and get the error
# 

Caused by: java.lang.ClassCastException: org.apache.jsp.tag.web.textField_tag cannot be cast to org.apache.jsp.tag.web.textField_tag
    at org.apache.jsp.WEB_002dINF.jsp.manufacturer.form_jsp._jspx_meth_cejug_005ftextField_005f0(form_jsp.java:257)
    at org.apache.jsp.WEB_002dINF.jsp.manufacturer.form_jsp._jspService(form_jsp.java:97)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69) [jastow-1.0.0.CR1.jar:1.0.0.CR1]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:366) [jastow-1.0.0.CR1.jar:1.0.0.CR1]
    ... 103 more
![04](https://f.cloud.github.com/assets/6443576/2025481/6d59fd6a-887c-11e3-8d0d-7b186d965aa1.png)

**Comment by helio-frota** [comment]
tested with and without     jsp-configuration development="true"
works only with full publish here.

**Comment by efraimgentil** [comment]
Bug, apparently it is already fixed to the final release 
https://issues.jboss.org/browse/WFLY-2690

**Comment by helio-frota** [comment]
Good catch @efraimgentil !
the comment :
https://issues.jboss.org/browse/WFLY-2690

**Comment by paulojribp** [comment]
Great.. if it does not depends of Hurraa I will close this issue. Thanks.
